on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: armandojose009
        password: a18234324
        repository: thelibrary_web
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}